<?php           if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_606fcc23e9aa0',
    'title' => 'Block: Blog Posts',
    'fields' => array(
        array(
            'key' => 'field_606fcc2905865',
            'label' => 'Blog Posts',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_61d670adbc209',
            'label' => 'Title',
            'name' => 'title',
            'type' => 'text',
            'instructions' => 'Optional - Will Display an H2 heading on the page',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_606fcc5e05867',
            'label' => 'How to Pull Posts?',
            'name' => 'how_to_pull_posts',
            'type' => 'select',
            'instructions' => 'What method should be used to display posts within this block?',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'category' => 'Category-based',
                'manual' => 'Manually-selected Posts',
            ),
            'default_value' => false,
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 0,
            'return_format' => 'value',
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_606fcc9505868',
            'label' => 'How Many Posts?',
            'name' => 'how_many_posts',
            'type' => 'number',
            'instructions' => 'How many posts to dynamically pull from the selected Category',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_606fcc5e05867',
                        'operator' => '==',
                        'value' => 'category',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '30',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
        ),
        array(
            'key' => 'field_606fccbd05869',
            'label' => 'Which Category?',
            'name' => 'which_category',
            'type' => 'taxonomy',
            'instructions' => 'What category should we pull posts from?',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_606fcc5e05867',
                        'operator' => '==',
                        'value' => 'category',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '40',
                'class' => '',
                'id' => '',
            ),
            'taxonomy' => 'category',
            'field_type' => 'select',
            'allow_null' => 0,
            'add_term' => 0,
            'save_terms' => 0,
            'load_terms' => 0,
            'return_format' => 'object',
            'multiple' => 0,
        ),
        array(
            'key' => 'field_620d3912a8a1f',
            'label' => 'Offset',
            'name' => 'offset',
            'type' => 'number',
            'instructions' => 'How many posts would you like to offset? To skip the first post, set offset to 1, etc.',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_606fcc5e05867',
                        'operator' => '==',
                        'value' => 'category',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '30',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
        ),
        array(
            'key' => 'field_606fcd07b6023',
            'label' => 'Select the Posts to Display',
            'name' => 'select_the_posts_to_display',
            'type' => 'post_object',
            'instructions' => 'Manually select the posts that should be displayed here',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_606fcc5e05867',
                        'operator' => '==',
                        'value' => 'manual',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(
                0 => 'post',
            ),
            'taxonomy' => '',
            'allow_null' => 0,
            'multiple' => 1,
            'return_format' => 'object',
            'ui' => 1,
        ),
        array(
            'key' => 'field_606fcd54b6024',
            'label' => 'Style',
            'name' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_61d668614d07c',
            'label' => 'Which Layout Style Should Be Used?',
            'name' => 'layout_style',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'Hero' => 'Hero',
                'Featured' => 'Featured',
                'Grid' => 'Grid',
            ),
            'default_value' => false,
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '',
        ),
        array(
            'key' => 'field_61f3900f872c9',
            'label' => 'Buttons',
            'name' => 'buttons',
            'type' => 'group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_61d668614d07c',
                        'operator' => '==',
                        'value' => 'Hero',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_61f3901f0b765',
                    'label' => 'Button 1 Text',
                    'name' => 'button_1_text',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_61f390240b766',
                    'label' => 'Button 1 Link',
                    'name' => 'button_1_link',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_61f3902b0b767',
                    'label' => 'Button 2 Text',
                    'name' => 'button_2_text',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_61f3902f0b768',
                    'label' => 'Button 2 Link',
                    'name' => 'button_2_link',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_61d6688e4d07d',
            'label' => 'Display Category Filters & Search?',
            'name' => 'category_filter_search',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_61d668614d07c',
                        'operator' => '==',
                        'value' => 'Grid',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/blog-posts',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));

endif;      